### ISSUE TITLE
Double markers on mobile

### ISSUE THREAD

**Issue by jieter** [leaflet-extras/leaflet.sprite#1]
On the example page on my Galaxy S2 in Chrome I see this:
![2013-03-13 19 16 59](https://f.cloud.github.com/assets/1470389/255351/8b576402-8c0a-11e2-8717-1e76aa4eae60.png)

Exactly the same on the stock browser btw.
![2013-03-13 19 20 40](https://f.cloud.github.com/assets/1470389/255364/c0a3ebc6-8c0a-11e2-8fe7-e42d343a4c1d.png)

**Comment by calvinmetcalf** [comment]
I'm getting it on my Razr too let me look into it.

**Comment by calvinmetcalf** [comment]
it would seem leaflet is incorectly identifing them as retina displays, reverted including leaflet 5.0 from 5.1 and that did the trick for my phone

**Comment by jieter** [comment]
Does not fix it for me (cleared the cache)...

**Comment by calvinmetcalf** [comment]
yeah wtf it worked for me for a second and now it isn't

**Comment by calvinmetcalf** [comment]
ok I turned off retina as an option and now it works for real this time

**Comment by calvinmetcalf** [comment]
yeah now I need to figure out why my very non retina phone is getting tagged retina

**Comment by calvinmetcalf** [comment]
I have it working on my phone and my tablet now

**Comment by jieter** [comment]
confirmed.

**Comment by calvinmetcalf** [comment]
for some reason in the previous version I had to double the size of the markers with the retina, but not anymore, weird but hey this is why I wanted to bring it into the org.
